server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

spring:
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: neo4j_pwd
    datasource:
        url: jdbc:postgresql://localhost:5433/diglearn
        username: postgres
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        open-in-view: false            